export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_PREFIX_HOME="$HOME/.local"
export XDG_DATA_HOME="$XDG_PREFIX_HOME/share"
export XDG_STATE_HOME="$XDG_PREFIX_HOME/state"
export XDG_BIN_HOME="$XDG_PREFIX_HOME/bin"
export PATH="$XDG_BIN_HOME:$PATH"
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CACHE_HOME"
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_STATE_HOME"
mkdir -p "$XDG_BIN_HOME"

export skip_global_compinit=1
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"
export CABAL_DIR="$XDG_CACHE_HOME/cabal"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GHCUP_USE_XDG_DIRS=1
export STACK_ROOT="$XDG_DATA_HOME/stack"
export GOPATH="$XDG_DATA_HOME/go"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export KDEHOME="$XDG_CONFIG_HOME/kde"
export LEIN_HOME="$XDG_DATA_HOME/lein"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export POETRY_HOME="$XDG_DATA_HOME/poetry"
export MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/micromamba"
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export SSB_HOME="$XDG_DATA_HOME/zoom"
