return {
  setup = {
    "rcarriga/nvim-notify", -- notifications
    "mbbill/undotree", -- undo tree
    "ziontee113/color-picker.nvim",
    "klen/nvim-config-local", -- load local config
    "mhinz/vim-startify", -- startify
    {
      "pysan3/autosession.nvim", -- restore previous session
      -- "~/Git/autosession.nvim",
      requires = { "mhinz/vim-startify" },
    },
    "preservim/tagbar", -- show tagbar on left generated by ctags (require command build)
    "windwp/nvim-spectre", -- better search and replace plugin
    "numToStr/Navigator.nvim",
    { "folke/noice.nvim", requires = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" } },
  },
  install = {
    { "romainl/vim-cool", config = "vim.g.CoolTotalMatches = 1" },
    "AndrewRadev/bufferize.vim",
    { "inkarkat/vim-SearchHighlighting", requires = { "inkarkat/vim-ingo-library" } }, -- search word under corsor
  },
}
