-- dap global keymaps (runs everywhere)
local dap_prefix = "<leader>d"
vim.keymap.set("n", "<F5>", function()
  require("dap").continue()
end, { desc = "dap.continue()" })
vim.keymap.set("n", dap_prefix .. "b", function()
  require("dap").toggle_breakpoint()
end, { desc = "dap.toggle_breakpoint()" })
vim.keymap.set("n", dap_prefix .. "B", function()
  require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "dap.set_breakpoint(vim.fn.input(Breakpoint condition: ))" })
vim.keymap.set("n", dap_prefix .. "e", function()
  require("dap").set_exception_breakpoints({ "all" })
end, { desc = "dap.set_exception_breakpoints({ all })" })
vim.keymap.set("n", dap_prefix .. "r", function()
  require("dap").run_last()
end, { desc = "dap.run_last()" })
vim.keymap.set("n", dap_prefix .. "R", function()
  require("dap").clear_breakpoints()
end, { desc = "dap.clear_breakpoints()" })
vim.keymap.set("n", dap_prefix .. "g", function()
  require("dap").session()
end, { desc = "dap.session()" })
vim.keymap.set("n", dap_prefix .. "a", function()
  require("debugHelper").attach()
end, { desc = "debugHelper.attach()" })
vim.keymap.set("n", dap_prefix .. "A", function()
  require("debugHelper").attachToRemote()
end, { desc = "debugHelper.attachToRemote()" })

-- language specific configs
-- follow: https://github.com/Pocco81/dap-buddy.nvim/issues/71 for more updates

local dap_prefix_python = dap_prefix .. "p"
vim.keymap.set("n", dap_prefix_python .. "n", function ()
   require("dap-python").test_method({})
end, { desc = "dap_python.test_method" })
vim.keymap.set("n", dap_prefix_python .. "f", function ()
   require("dap-python").test_class({})
end, { desc = "dap_python.test_class" })
vim.keymap.set("v", dap_prefix_python .. "s", function ()
   require("dap-python").debug_selection({})
end, { desc = "dap_python.debug_selection" })
