-- telescope dap bindings
local ts_prefix_dap = vim.g.personal_options.prefix.telescope .. "d"
vim.keymap.set("n", ts_prefix_dap .. "m", function()
  require("telescope").extensions.dap.commands({})
end, { desc = "ts.dap.commands({})" })
vim.keymap.set("n", ts_prefix_dap .. "c", function()
  require("telescope").extensions.dap.configurations({})
end, { desc = "ts.dap.configurations({})" })
vim.keymap.set("n", ts_prefix_dap .. "b", function()
  require("telescope").extensions.dap.list_breakpoints({})
end, { desc = "ts.dap.list_breakpoints({})" })
vim.keymap.set("n", ts_prefix_dap .. "v", function()
  require("telescope").extensions.dap.variables({})
end, { desc = "ts.dap.variables({})" })
vim.keymap.set("n", ts_prefix_dap .. "f", function()
  require("telescope").extensions.dap.frames({})
end, { desc = "ts.dap.frames({})" })
