local ts_prefix = vim.g.personal_options.prefix.telescope

-- telescope fzf bindings
vim.keymap.set("n", ts_prefix .. "f", function()
  require("telescope.builtin").buffers()
end, { desc = "ts.buffers" })
vim.keymap.set("n", ts_prefix .. "p", function()
  require("telescope.builtin").git_files()
end, { desc = "ts.git_files" })
vim.keymap.set("n", ts_prefix .. "l", function()
  require("telescope.builtin").find_files()
end, { desc = "ts.find_files" })
vim.keymap.set("n", ts_prefix .. "s", function()
  require("telescope.builtin").live_grep()
end, { desc = "ts.live_grep" })
vim.keymap.set("n", ts_prefix .. "h", function()
  require("telescope.builtin").help_tags()
end, { desc = "ts.help_tags" })
vim.keymap.set("n", ts_prefix .. "r", function()
  require("telescope.builtin").resume()
end, { desc = "ts.resume" })
vim.keymap.set("n", ts_prefix .. "j", function()
  require("telescope.builtin").jumplist()
end, { desc = "ts.jumplist" })
vim.keymap.set("n", ts_prefix .. "e", function()
  require("telescope.builtin").symbols()
end, { desc = "ts.symbols" })
vim.keymap.set("n", ts_prefix .. "C", function()
  require("telescope.builtin").commands()
end, { desc = "ts.commands" })
vim.keymap.set("n", ts_prefix .. "c", function()
  require("telescope.builtin").command_history()
end, { desc = "ts.command_history" })
vim.keymap.set("n", ts_prefix .. "i", function()
  require("telescope").extensions.media_files.media_files()
end, { desc = "ts.media_files" })

-- telescope lsp bindings
vim.keymap.set("n", ts_prefix .. "t", function()
  require("telescope.builtin").lsp_document_symbols()
end, { desc = "ts.lsp_document_symbols" })
vim.keymap.set("n", ts_prefix .. "y", function()
  require("telescope.builtin").lsp_workspace_symbols()
end, { desc = "ts.lsp_workspace_symbols" })
vim.keymap.set("n", ts_prefix .. "m", "<Cmd>TodoTelescope<CR>", { desc = "TodoTelescope @folke/todo-comments.nvim" })

-- telescope git bindings
local ts_prefix_git = ts_prefix .. "g"
vim.keymap.set("n", ts_prefix_git .. "c", function()
  require("telescope.builtin").git_commits()
end, { desc = "ts.git_commits" })
vim.keymap.set("n", ts_prefix_git .. "l", function()
  require("telescope.builtin").git_bcommits()
end, { desc = "ts.git_bcommits" })
vim.keymap.set("n", ts_prefix_git .. "b", function()
  require("telescope.builtin").git_branches()
end, { desc = "ts.git_branches" })

-- telescope other bindings
vim.keymap.set("n", "<leader>" .. ts_prefix .. "c", function()
  require("telescope.builtin").colorscheme()
end, { desc = "ts.colorscheme" })
